name: Performance Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  performance-tests:
    runs-on: ubuntu-latest
    env:
       AUTH_TOKEN: ${{ secrets.AUTHORIZATION }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Artillery
        run: npm install -g artillery

      - name: Debug - List files
        run: ls -R

      - name: Run Load Tests
        run: |
          mkdir -p reports
          
          artillery run load.yml --output reports/load-results.json

      - name: Upload All Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-test-reports
          path: reports/
