name: Performance Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:   # for manual trigger

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Artillery
        run: npm install -g artillery

      - name: Run Load Test
        run: |
          mkdir -p reports
          artillery run stress-test.yml --output reports/results.json

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: load-test-report
          path: reports/results.json
